### ISSUE TITLE
Why not use redis for caching?

### ISSUE THREAD

**Issue by pingrunhuang** [Sentdex/socialsentiment#7]
I saw the code is using a lot of sqlite for caching, might if I asked why not redis?

**Comment by daniel-kukiela** [comment]
It is using sqlite as a database - to store data.

The other use is a cache class. sqlite is used there only for someting named 'dev server', for production server we are using memcached for caching.

Which case you are reffering to?

**Comment by pingrunhuang** [comment]
I'm referring to the first use case that you mentioned. I'm quite confused why switching caching tools from SQLite to memcache instead of sticking to one tool. And regarding the second use case, seems like redis could provide more memory for caching, why not use redis for this scenario.
I'm just out of curious and thanks very much for the answer ;)

**Comment by daniel-kukiela** [comment]
Looks like you are mixing two thing because you are still using term `cache`.
It's not a cache, but a relational database used to store all tweets. Redis is not a database engine. So for a database we are using sqlite, and possibly MySQL in a future.

Second case is a cache. Why whould we force to install Memcached on dev server? There's no need to do that because sqlite is more than sufficient for that task and it's built in python. For a production server - we can't use sqlite here (but we could use MySQL for example), Memcached is our tool of choice for that task.

`seems like redis could provide more memory for caching`
That is not true, you can set Memcached to use all the RAM you have.

**Comment by pingrunhuang** [comment]
Thanks a lot for the explanation, I will close the issue here.
